# Numpy

## Numpy'a giriş
*   Numpy nedir ve neden kullanılır?
*   Python listeleri ve numpy
*   Numpy'ın temel avantajları

In [ ]:
# Numpy kurulumu -> pip install numpy
# colab'da var

In [ ]:
import numpy as np

### Neden Numpy
* python listeleri matematiksel işlemlerde yavaştır.

In [ ]:
import time

py_list = list(range(1000000))
start = time.time()
py_result = [x * 2 for x in py_list]
end = time.time()
print("python liste süresi: ", end - start)

python liste süresi:  0.06047177314758301

### Numpy avantajları
* Hız: C dili ile yazıldığı için
* Bellek verimliliği
* Vektörel işlemler
* Zengin fonksiyon desteği: Matematiksel, istatistik, lineer cebir

## Numpy Arrays
* Array oluşturma yöntemleri
* Array'lerin temel özellikleri: (ndim, shape, dtype, size)
* python liste -> numpy array
* Array veri tipleri

###Numpy Array oluşturma

In [ ]:
# Tek boyutlu array oluştrma - vektör
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]

In [ ]:
# iki boyutlu array (Matris)
arr2 = np.array([[1, 2, 3],[4, 5, 6 ]])
print(arr2)

[[1 2 3]
 [4 5 6]]

In [ ]:
# 3 boyutlu array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

### Array Özellikleri

In [ ]:
arr = np.array([[10, 20, 30],[40, 50, 60]])

print(arr)

[[10 20 30]
 [40 50 60]]

In [ ]:
# Kaç boyutlu?
print(f"Boyut sayısı (number of dimensions): {arr.ndim}")

print(f"Şekil: {arr.shape}") # satır x sütun

print(f"Eleman sayısı: {arr.size}") # toplam eleman

print(f"Veri tipi: {arr.dtype}")

print(f"Bellekteki byte boyutu : {arr.itemsize}") # kapladığı alan

Boyut sayısı (number of dimensions): 2
Şekil: (2, 3)
Eleman sayısı: 6
Veri tipi: int64
Bellekteki byte boyutu : 8

### Python listesi <--> Numpy Array

In [ ]:
py_list = [1, 2, 3, 4, 5]

arr = np.array(py_list)
print(arr)
type(arr)

[1 2 3 4 5]

numpy.ndarray

In [ ]:
back_to_list = arr.tolist()
type(back_to_list)

list

### Veri tipleri

In [ ]:
arr1 = np.array([1,2,3], dtype = np.float32)
print(arr1)

[1. 2. 3.]

### Array oluşturma fonksiyonları

In [ ]:
print(f"Sıfırdan oluşan array: \n {np.zeros((2,3))}")

Sıfırdan oluşan array:
 [[0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
print(f"Birlerden oluşan array: \n {np.ones((3,5))}")

Birlerden oluşan array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [ ]:
print(f"Aralık ile array (0 dan 10 a ikişer artış): \n {np.arange(0,10,2)}") # ilk eleman dahil son eleman değil(10)

Aralık ile array (0 dan 10 a ikişer artış):
 [0 2 4 6 8]

In [ ]:
print(f"eşit aralıklarla array: \n {np.linspace(0,10,5)}") # ilk eleman dahil son eleman dahil

eşit aralıklarla array:
 [ 0.   2.5  5.   7.5 10. ]

## Dizi oluşturma fonksiyonları
* 0 ve 1 lerden oluşan diziler
* aralıklı sayılar
* kimlik (identity) matris
* boş diziler
* tekrar eden diziler

In [ ]:
# 0 ve 1 den oluşan diziler
import numpy as np

In [ ]:
print(f"zeros: \n {np.zeros((2,3))}")
print(f"ones:\n {np.ones((2,3))}")
print(f"full: \n {np.full((2,3), 5)}") # 2 x 3 lük array 5 ile doldurulmuş

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
full:
 [[5 5 5]
 [5 5 5]]

In [ ]:
# arrange, linspace, logspace

print(f"arange: \n {np.arange(10)}")

print(f"linspace: \n {np.linspace(0,1,5)}")

print(f"logspace: \n {np.logspace(0,3,4)}") # 10^0 ve 10^3 arasunda logaritmik olarak 4 tane sayı oluştur

arange:
 [0 1 2 3 4 5 6 7 8 9]
linspace:
 [0.   0.25 0.5  0.75 1.  ]
logspace:
 [   1.   10.  100. 1000.]

In [ ]:
# eye ve identity
print(f"3x3 lük birim matris: \n {np.eye(3)}")

print(f"4x4 lük birim matris: \n {np.identity(4)}")

3x3 lük birim matris:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4x4 lük birim matris:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [ ]:
# empty ve empty_like

print(f"empty: \n {np.empty((2,3), dtype=np.int32)}")

empty:
 [[         0 1072693248          0]
 [1072693248          0 1072693248]]

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
np_empty_like = np.empty_like(arr)
print(f"empty_like: \n {np_empty_like}")

empty_like:
 [[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]

In [ ]:
# tile ve repeat

print(f"repeat: \n {np.repeat([1,2,3], 3)}")

print(f"tile: \n {np.tile([1,2,3], 3)}")

repeat:
 [1 1 1 2 2 2 3 3 3]
tile:
 [1 2 3 1 2 3 1 2 3]

## indeksleme ve slicing
* Temel indeksleme (Tek veya çok boyutlu)
* fancy indexing (liste ve array ile seçim)
* boolean indexing (Şarta göre seçim)
* atama ile dizi değiştirme
* view ve copy

### Temel indeksleme

In [ ]:
import numpy as np

# Tek boyutlu dizi

arr1 = np.array([10,20,30,40])
arr1

array([10, 20, 30, 40])

In [ ]:
print(f"ilk eleman: {arr1[0]}")
print(f"son eleman: {arr1[-1]}")

ilk eleman: 10
son eleman: 40

In [ ]:
print(f"ilk 3 eleman: {arr1[:3]}")

ilk 3 eleman: [10 20 30]

In [ ]:
print(f"son 2 eleman: {arr1[-2:]}")

son 2 eleman: [30 40]

In [ ]:
arr2 = np.array([[10,20,30],[40,50,60], [70,80,90]])
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
print(f"2. satır 3. sütundaki eleman: {arr2[1,2]}")

2. satır 3. sütundaki eleman: 60

In [ ]:
print(f"ilk satır: {arr2[0,:]}")

ilk satır: [10 20 30]

In [ ]:
print(f"2. sütun: {arr2[:,2]}")

2. sütun: [30 60 90]

### Fancy indexing (Liste veya array ile seçim)

In [ ]:
arr = np.array([10,20,30,40,50])

# belirli indexleri seçmek istediğimizde
fancy = arr[[0,2,4]]
print(fancy)

[10 30 50]

In [ ]:
# iki boyutlu örnek

arr2 = np.array([[10,20,30],[40,50,60], [70,80,90]])

rows = [0,2]
cols = [0,1]
print(f"secilen elemanlar: {arr2[rows, cols]}")
arr2[[0,2],[0,0]]
arr2

secilen elemanlar: [10 80]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### Boolean indexing

In [ ]:

arr = np.array([5,10,15,20,25])

bool_index = arr[arr > 15]
print(f"boolean indexing: {bool_index}")

boolean indexing: [20 25]

In [ ]:
print(f"çift sayıları seç: {arr[arr % 2 == 1]}")

çift sayıları seç: [ 5 15 25]

### Atama ile dizi değiştirme

In [ ]:
arr = np.array([1,2,3,4,5])

arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [ ]:
arr[2:4] = [77,88] # 2 den 4 e kadar olan index i değiştik
arr

array([99,  2, 77, 88,  5])

### view vs Copy

In [ ]:
arr = np.array([10,20,30,40,50])

slice_view = arr[1:4]
slice_view[:] = 0
print(f"slice_view: {slice_view}")
print(f"arr: {arr}")

# Değişkeni başka bir değişkene atasakta ilk hali etkileniyor

slice_view: [0 0 0]
arr: [10  0  0  0 50]

In [ ]:
# Bu sorunu çözmek için copy

arr2 = np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

In [ ]:
slice_copy = arr2[1:4].copy()
slice_copy[:] = 0
print(f"slice_copy: {slice_copy}")
print(f"arr: {arr2}")

slice_copy: [0 0 0]
arr: [10 20 30 40 50]

## Dizi işlemleri
* skaler işlemler
* eleman bazlı işlemler
* evrensel fonksiyonlar
* matematiksel fonksiyonlar
* istatistiksel fonksiyonlar
* kümülatif işlemler

### Skaler işlemler

In [ ]:
import numpy as np

arr = np.array([10,20,30,40])

# Array bazlı
print(f"Çarpma: {arr * 3}")
print(f"her elemana 5 ekleme : {arr + 5}")
print(f"kare alma: {arr ** 2}")
print(f"karekök alma: {np.sqrt(arr)}")

Çarpma: [ 30  60  90 120]
her elemana 5 ekleme : [15 25 35 45]
kare alma: [ 100  400  900 1600]
karekök alma: [3.16227766 4.47213595 5.47722558 6.32455532]

In [ ]:
# eleman bazlı işlemler

arr1 = np.array([10,20,30,40])
arr2 = np.array([2,3,4,5])

print(f"toplama: {np.add(arr1, arr2)}")
print(f"çıkarma: {np.subtract(arr1, arr2)}")
print(f"çarpma: {np.multiply(arr1 , arr2)}")
print(f"bölme: {np.divide(arr1 , arr2)}")

toplama: [12 23 34 45]
çıkarma: [ 8 17 26 35]
çarpma: [ 20  60 120 200]
bölme: [5.         6.66666667 7.5        8.        ]

### Universal functions
* sqrt
* exp
* log
* sin
* cos...

In [ ]:
arr = np.array([1,4,9,16,25])

print(f"karekök: {np.sqrt(arr)}")
print(f"exponential: {np.exp(arr)}")
print(f"log: {np.log(arr)}")
print(f"sin: {np.sin(arr)}")
print(f"cos: {np.cos(arr)}")

karekök: [1. 2. 3. 4. 5.]
exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
cos: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]

### istatiksel fonksiyonlar
* sum, min, ort, median, std, var

In [ ]:
arr = np.array([5,10,15,20,25])

print(f"toplam: {np.sum(arr)}")
print(f"minimum: {np.min(arr)}")
print(f"maksimum: {np.max(arr)}")
print(f"ortalama: {np.mean(arr)}")
print(f"medyan: {np.median(arr)}")
print(f"standart sapma: {np.std(arr)}")
print(f"varyans: {np.var(arr)}")
print(f"min değerin indexi : {np.argmin(arr)}")
print(f"max değerin indexi : {np.argmax(arr)}")

toplam: 75
minimum: 5
maksimum: 25
ortalama: 15.0
medyan: 15.0
standart sapma: 7.0710678118654755
varyans: 50.0
min değerin indexi : 0
max değerin indexi : 4

In [ ]:
arr = np.array([1,2,3,4,5])

print(f"kümülatif toplam: {np.cumsum(arr)}")
print(f"kümülatif çarpım: {np.cumprod(arr)}")

kümülatif toplam: [ 1  3  6 10 15]
kümülatif çarpım: [  1   2   6  24 120]

### Mini proje- Günlük adım analizi
* 7 günlük adım sayıları dizisi oluştur
* toplam adım sayısı
* günlük ort. adım sayısı
* en çok adım atılan gün ve değeri
* kümülatif toplam ile adım sayısını göster

In [ ]:
adim_sayisi = np.array([6500,7000, 2600, 3000, 10000, 5500, 8000])

print(f"toplam_adim = {np.sum(adim_sayisi)}")
print(f"ortalama adim sayısı= {round(np.mean(adim_sayisi), 2)}")
print(f"en çok adım atan gün = {np.argmax(adim_sayisi) + 1} , adım sayısı= {np.max(adim_sayisi)}")
print(f"kümülatif toplam = {np.cumsum(adim_sayisi)} ")

toplam_adim = 42600
ortalama adim sayısı= 6085.71
en çok adım atan gün = 5 , adım sayısı= 10000
kümülatif toplam = [ 6500 13500 16100 19100 29100 34600 42600]

## Shape (Şekil) işlemleri
* Dizinin şeklini değiştirme
* Tek boyuta dönüştürme
* Transpose alma
* Boyut ekleme veya silme
* Dizileri birleştirme / ayırma

### Dizinin şeklini değiştirme

In [ ]:
import numpy as np

arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
reshaped = arr.reshape(3,4)
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Tek boyuta dönüştürme

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(f"tek boyuta dönüştürme: {arr.ravel()}") # view döner
print(f"tek boyuta dönüştürme: {arr.flatten()}") # copy döner

tek boyuta dönüştürme: [1 2 3 4 5 6]
tek boyuta dönüştürme: [1 2 3 4 5 6]

### Transpos alma

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(f"transpos alma: \n {arr.T}")

transpos alma:
 [[1 4]
 [2 5]
 [3 6]]

### Boyut ekleme ve silme

In [ ]:
arr = np.array([1,2,3])

In [ ]:
arr.shape

(3,)

In [ ]:
expanded = np.expand_dims(arr, axis=0) # satır ekle
expanded.shape

(1, 3)

In [ ]:
squeezd = np.squeeze(expanded) # eklenen boyutu sildi
squeezd.shape

(3,)

### Dizileri birleştirme

In [ ]:
# Genel birleştirme
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

print(f"birleştirme: \n {np.concatenate((a,b), axis=0)}")

birleştirme:
 [[1 2]
 [3 4]
 [5 6]]

In [ ]:
# dikey birleştirme

vstacked = np.vstack((a,b))
print(f"dikey birleştirme: \n {vstacked}")

dikey birleştirme:
 [[1 2]
 [3 4]
 [5 6]]

In [ ]:
# yatay birleştirme

hstacked = np.hstack((a,np.array([[7],[8]])))
print(f"yatay birleştirme: \n {hstacked}")

yatay birleştirme:
 [[1 2 7]
 [3 4 8]]

### Dizileri ayırma

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(f"split: \n {np.split(arr, 5)}") # 5 eşit parçaya ayırır

split:
 [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
print(f"split: \n {np.array_split(arr,4 )}")

split:
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

### Mini proje - Görüntü Verisi Şekil dönüşümü
* 0-255 arasında rastgele sayılardan oluşsun, boyutu 28x28 olsun
* Bu resmi vektöre çevir (28x28 = 784)
* tekrar orijinal hale çevirelim

In [ ]:
import numpy as np

np.random.seed(0) # Rastgelelikler aynı olsun diye

image = np.random.randint(0,256, size=(28,28))

In [ ]:
# Tek boyutlu vektör yap
flat = image.flatten()
flat.shape

(784,)

In [ ]:
# Orjinale çevir
reshaped = flat.reshape(28,28)
reshaped.shape

(28, 28)

## Rastgele Sayılar
* rand, randn, randint
* choice, permutation, shuffle
* olasılık dağılımları (binom, poison, normal, uniform)
* seed kullanımı

### rand, randn, randint

In [ ]:
import numpy as np

# 0-1 arasında rastgele sayı üret (uniform dağılım)

print(f"rand : {np.random.rand(3,3)}")

# Normal dağılıma göre rastgele sayı üret

print(f" \n randn: {np.random.randn(3,3)}")

# Belirli bir aralıkta rastgele tam sayılar üret

print(f"\n randint: {np.random.randint(1,10, size=(3,3))}")

rand : [[0.01162828 0.76230329 0.05945873]
 [0.2248549  0.67562621 0.04081951]
 [0.23236553 0.12004932 0.63457067]]

 randn: [[ 0.52405846 -0.66255893 -2.36971875]
 [ 1.40355501  0.04448759  2.29941525]
 [ 0.96216894 -1.01549771  0.01222168]]

 randint: [[4 7 5]
 [1 6 5]
 [3 9 8]]

### Belirli bir kümeden rastgele seçim

In [ ]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
print(f"tek seçim: \n {np.random.choice(arr)}")
print(f"çoklu seçim: \n {np.random.choice(arr, size=5)}")
print(f"tekrarsız seçim: \n {np.random.choice(arr, 3, replace = False)}")

tek seçim:
 10
çoklu seçim:
 [50 40 50 10 20]
tekrarsız seçim:
 [10 40 50]

### Permütassyon ve shuffle

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Yeni karışık dizi return eder
print(f"Permutation : {np.random.permutation(arr)}")

Permutation : [9 6 2 7 8 4 5 0 3 1]

In [ ]:
# Shuffle yerinde karıştırma - return etmez

print(f"Shuffle : {np.random.shuffle(arr)}") # None döner
arr

Shuffle : None

array([3, 6, 1, 2, 9, 4, 5, 7, 8, 0])

### Olasılık dağılımarı

In [ ]:
binom = np.random.binomial(n = 10, p = 0.5, size=5)
binom

array([6, 3, 7, 6, 6])

In [ ]:
poisson = np.random.poisson(lam = 5, size=5)
poisson

array([10,  6,  9,  8,  6])

In [ ]:
normal = np.random.normal(loc=0, scale=1, size=5) # ort 0, std 1
normal

array([-1.10549142, -0.83584336, -1.16203211,  0.927511  ,  0.13054015])

In [ ]:
uniform = np.random.uniform(low=0, high=1, size=5)
uniform

array([0.52978515, 0.57339896, 0.3416344 , 0.74175262, 0.20796052])

### Seed : Rastgele sayıların tekrarlanabilir olmasını sağlar

In [ ]:
np.random.seed(42)

np.random.randint(0,15,10)

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9])

## İstatistik ve veri analizi
* ortalama, median, mode
* varyans, std
* percentile, qantile
* kolerasyon ve kovaryans

### Ortalama median mode

In [ ]:
import numpy as np

data = np.array([10,20,30,40,50,50,50,60])

In [ ]:
print(f"ortalama: {np.mean(data)}")

ortalama: 38.75

In [ ]:
print(f"median: {np.median(data)}")

from scipy import stats
print(f"mod: {stats.mode(data)[0]}")

median: 45.0
mod: 50

### Varyans ve standart sapma

In [ ]:
print(f"varyans: {np.var(data)}")
print(f"standart sapma: {np.std(data)}")

varyans: 260.9375
standart sapma: 16.153559979150106

### Percentile ve Quantile
* percentile : 0-100 yüzdelik
* quantile : 0-1 oran

In [ ]:
print(f"25. percentile: {np.percentile(data, 25)}")
print(f"50. percentile: {np.percentile(data, 50)}") # median
print(f"75. percentile: {np.percentile(data, 75)}")

25. percentile: 27.5
50. percentile: 45.0
75. percentile: 50.0

In [ ]:
print(f"25. quantile: {np.quantile(data, 0.25)}")
print(f"50. quantile: {np.quantile(data, 0.50)}")

25. quantile: 27.5
50. quantile: 45.0

### Korelasyon ve kovaryans
* pozitif: iki değişken birlikte artar
* iki değişken birlikte azalır
* 0 ise ilişki yok

In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

print(f"korelasyon:\n {np.corrcoef(x,y)}")
print(f"kovaryans:\n {np.cov(x,y)}")

korelasyon:
 [[1. 1.]
 [1. 1.]]
kovaryans:
 [[ 2.5  5. ]
 [ 5.  10. ]]

## Lineer Cebir
* Skaler çarpım
* Matris çarpımı
* Determinant
* Ters matris
* rank
* eligen değerleri ve vektörleri
* Lineer denklem çözümü

In [ ]:
# Skaler çarpım

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(f"skaler çarpım: {np.dot(a,b)}")
print(f"skaler çarpım: {np.vdot(a,b)}")

skaler çarpım: 32
skaler çarpım: 32

In [ ]:
# Matris çarpımı
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(f"mat mul: \n {np.matmul(a,b)}")

mat mul:
 [[19 22]
 [43 50]]

In [ ]:
# determinant hesabı

a = np.array([[1,2],[3,4]])

print(f"determinant: {np.linalg.det(a)}")

determinant: -2.0000000000000004

In [ ]:
# Ters matris

a = np.array([[1,2],[3,4]])

print(f"ters matris: \n {np.linalg.inv(a)}")

ters matris:
 [[-2.   1. ]
 [ 1.5 -0.5]]

In [ ]:
# Rank
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(f"rank: {np.linalg.matrix_rank(a)}")

rank: 2

In [ ]:
# eigen değerler ve vektörler

a = np.array([[1,2],[3,4]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print(f"eigen values: {eigenvalues}")
print(f"eigen vectors: \n {eigenvectors}")

eigen values: [-0.37228132  5.37228132]
eigen vectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

In [ ]:
# Lineer denklem çözümü

"""
2x + y = 5
x - y = 1
"""

a = np.array([[2,1],[1,-1]])
b = np.array([5,1])

solution = np.linalg.solve(a,b)
print(f"x ve y: {solution}")

x ve y: [2. 1.]

## Maskeler ve koşullu işlemler

In [ ]:
# Boolean diziler

import numpy as np

arr = np.array([10,20,30,40,50])

mask = arr > 25
mask

print(arr[mask])

[30 40 50]

In [ ]:
# where komutuna göre seçim

arr = np.array([10,20,30,40,50])

result = np.where(arr < 25 , 0 ,arr) # küçük olanlar 0, büyük olanlar arr kalsın

result

array([ 0,  0, 30, 40, 50])

In [ ]:
# select: birden fazla koşul

arr = np.array([10,20,30,40,50])

conditions = [arr < 20, arr < 40, arr >= 40]

choises = ["kucuk" , "orta", "buyuk"]

labels = np.select(conditions, choises , default = "bilinmiyor")

labels

array(['kucuk', 'orta', 'orta', 'buyuk', 'buyuk'], dtype='<U10')

In [ ]:
# non zero

arr = np.array([ 10,0,20,30,40,50])

print(np.nonzero(arr))

(array([0, 2, 3, 4, 5]),)

In [ ]:
# any ve all

arr = np.array([10,20,30,40,50])

print(f"Herhangi biri 30 dan büyük mü : {np.any(arr > 30)}")
print(f"Hepsi 5 den büyük mü : {np.all(arr > 5)}")
print(f"Hepsi 30 dan büyük mü : {np.all(arr > 30)}")

Herhangi biri 30 dan büyük mü : True
Hepsi 5 den büyük mü : True
Hepsi 30 dan büyük mü : False

## Dosya işlemleri
* save ve load

In [ ]:
import numpy as np

In [ ]:
arr = np.array([10,20,30,40,50])

np.save("data.npy", arr)

In [ ]:
loaded_array = np.load("data.npy")
loaded_array

array([10, 20, 30, 40, 50])

# Pandas

## Pandasa giriş
* Numpy üzerine inşa edilmiş bir python kütüphanesidir
* Tablo şeklinde veriler ile çalışmayı kolaylaştırır
* Temel veri yapıları
    * Series: Tek boyutlu
    * DataFrame: iki boyutlu

In [ ]:
# pip install pandas
import pandas as pd

In [ ]:
# Seriler
s = pd.Series([10,20,30,40,50], index = ["a","b","c","d","e"])
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
# DataFrame - dictionary ile tanımla sonra frame'e at

data = {
    "isim": ["ahmet", "mehmet", "ali"],
    "yas": [25,30,35],
    "sehir" : ["Ankara", "Elazığ", "İstanbul"]
}

df = pd.DataFrame(data)
df

     isim  yas     sehir
0   ahmet   25    Ankara
1  mehmet   30    Elazığ
2     ali   35  İstanbul

In [ ]:
print(f" Şekil (satır/sütun): {df.shape}")
print(f"\n İndexler: {df.index}")
print(f"\n Sütunlar: {df.columns}")
print(f"\n Değerler: {df.values}")
print(f"\n Veri tipi: \n{df.dtypes}")

 Şekil (satır/sütun): (3, 3)

 İndexler: RangeIndex(start=0, stop=3, step=1)

 Sütunlar: Index(['isim', 'yas', 'sehir'], dtype='object')

 Değerler: [['ahmet' 25 'Ankara']
 ['mehmet' 30 'Elazığ']
 ['ali' 35 'İstanbul']]

 Veri tipi:
isim     object
yas       int64
sehir    object
dtype: object

## Pandas Seriler
* Seri oluşturma yöntemleri
* Index yapıları
* Temel özellikleri
* Indexleme ve slicing
* Temel fonksiyonlar

In [ ]:
# Seri oluşturma

s1 = pd.Series([10,20,30,40]) # Listeden seri oluşturma
s1

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s2 = pd.Series([10,20,30,40], index = ["a", "b", "c", "d"])
s2

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
# dict ten seri oluşturma
data = {
    "Ali": 55,
    "Ayşe": 45,       # Key'ler index oluyor
    "Mehmet": 25
}

s3 = pd.Series(data)
s3

Ali       55
Ayşe      45
Mehmet    25
dtype: int64

In [ ]:
# Temel özellikler

s = pd.Series([10,20,30,40], index = ["a", "b", "c", "d"])

print(f"Serinin değerleri: {s.values}")
print(f"Serinin indexleri: {s.index}")
print(f"Serinin eleman sayısı: {s.size}")

Serinin değerleri: [10 20 30 40]
Serinin indexleri: Index(['a', 'b', 'c', 'd'], dtype='object')
Serinin eleman sayısı: 4

In [ ]:
# indexleme ve slicing

s = pd.Series([10,20,30,40], index = ["a", "b", "c", "d"])
s

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
s["b"]

np.int64(20)

In [ ]:
s["a":"c"]  # slicing

a    10
b    20
c    30
dtype: int64

In [ ]:
s[0:2] # sayısla index

a    10
b    20
dtype: int64

In [ ]:
# Seriler üzerinde fonksiyonlar
print(f"Ortalama: {s.mean()}")
print(f"Toplam: {s.sum()}")
print(f"Max: {s.max()}")
print(f"std: {s.std()}")

Ortalama: 25.0
Toplam: 100
Max: 40
std: 12.909944487358056

In [ ]:
# Benzersiz değerler (unique)
s = pd.Series([10,20,30,30,30,40,50,50])

s.unique()

array([10, 20, 30, 40, 50])

In [ ]:
s.value_counts() # Her değerin veri setinde olma sayısı

30    3
50    2
10    1
20    1
40    1
Name: count, dtype: int64

## Pandas DataFrame
* DataFrame oluşturma yöntemleri
* Satır - Sütun seçimi
* DataFrame öz
* Sütun ekleme-silme

In [ ]:
# Sözcükler ile
data = {
    "isim": ["ahmet", "mehmet", "ali"],
    "yas": [25,30,35],
    "sehir" : ["Ankara", "Elazığ", "İstanbul"]
}

df = pd.DataFrame(data)
df

     isim  yas     sehir
0   ahmet   25    Ankara
1  mehmet   30    Elazığ
2     ali   35  İstanbul

In [ ]:
# Numpy arrayden oluşturma

import numpy as np

arr = np.array([[1,"Ali",25],
                [2,"Ayşe",30],
                [3,"Mehmet",35]
                ])

df2 = pd.DataFrame(arr, columns = ["id","isim","yas"])
df

     isim  yas     sehir
0   ahmet   25    Ankara
1  mehmet   30    Elazığ
2     ali   35  İstanbul

In [ ]:
# satır ve sütun seçimleri
# iloc, loc, indeksleme

print(df["yas"])
print(f"İlk 2 satır: \n {df.loc[:,"yas"]}")
print(f"İlk 2 satır: \n {df.iloc[:2]}")

0    25
1    30
2    35
Name: yas, dtype: int64
İlk 2 satır:
 0    25
1    30
2    35
Name: yas, dtype: int64
İlk 2 satır:
      isim  yas   sehir
0   ahmet   25  Ankara
1  mehmet   30  Elazığ

In [ ]:
print(df[["isim", "yas"]])

     isim  yas
0   ahmet   25
1  mehmet   30
2     ali   35

In [ ]:
# sütun ekleme-silme

df["puan"] = [100,200,300]
df

     isim  yas     sehir  puan
0   ahmet   25    Ankara   100
1  mehmet   30    Elazığ   200
2     ali   35  İstanbul   300

In [ ]:
df.drop("sehir", axis = 1, inplace = True) # axis = 1 -> sütun sil, inplace -> sil ve eşitle
df

     isim  yas  puan
0   ahmet   25   100
1  mehmet   30   200
2     ali   35   300

## Veri okuma ve kaydetme
* csv, excel ve json formatlarında kaydet
* sonra geri oku

In [ ]:
data = {
    "isim": ["Nisa", "Ahsen", "Polat", "Semih", "Sena", "Feyza", "Zeynep", "Yavuz", "Sehadet", "Enise"],
    "yas": [22, 22, 13, 16, 24, 25, 46, 45, 25, 44],
    "not": [100, 99, 45, 18, 74, 56, 100, 99, 95, 98]
}

df = pd.DataFrame(data)
df

      isim  yas  not
0     Nisa   22  100
1    Ahsen   22   99
2    Polat   13   45
3    Semih   16   18
4     Sena   24   74
5    Feyza   25   56
6   Zeynep   46  100
7    Yavuz   45   99
8  Sehadet   25   95
9    Enise   44   98

In [ ]:
# kaydet

df.to_csv("ogrenciler.csv", index = False)
df.to_excel("ogrenciler.xlsx", index = False)
df.to_json("ogrenciler.json", orient = "records", lines = True)

In [ ]:
# Tekrar oku

df_csv = pd.read_csv("ogrenciler.csv")
df_csv

      isim  yas  not
0     Nisa   22  100
1    Ahsen   22   99
2    Polat   13   45
3    Semih   16   18
4     Sena   24   74
5    Feyza   25   56
6   Zeynep   46  100
7    Yavuz   45   99
8  Sehadet   25   95
9    Enise   44   98

In [ ]:
df_excel = pd.read_excel("ogrenciler.xlsx")
df_json = pd.read_json("ogrenciler.json", lines = True)
df_excel

      isim  yas  not
0     Nisa   22  100
1    Ahsen   22   99
2    Polat   13   45
3    Semih   16   18
4     Sena   24   74
5    Feyza   25   56
6   Zeynep   46  100
7    Yavuz   45   99
8  Sehadet   25   95
9    Enise   44   98

In [ ]:
df_json

      isim  yas  not
0     Nisa   22  100
1    Ahsen   22   99
2    Polat   13   45
3    Semih   16   18
4     Sena   24   74
5    Feyza   25   56
6   Zeynep   46  100
7    Yavuz   45   99
8  Sehadet   25   95
9    Enise   44   98

## Veri inceleme ve özetleme
* ilk ve son satırlara bakma
* genel bilgiler (info, shape, columns)
* temel istatistiksel özellikler
* eksik değerler
* unique değerler

In [ ]:
# ilk ve son satırlara bakmak
import kagglehub
path = kagglehub.dataset_download("shivamb/netflix-shows")

Using Colab cache for faster access to the 'netflix-shows' dataset.

In [ ]:
df = pd.read_csv("/kaggle/input/netflix-shows/netflix_titles.csv")

In [ ]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.tail(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
# Genel bilgiler

df.shape

(8807, 12)

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
# Temel istatistiksel analiz

df.describe() # sayısal değerlerin

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [ ]:
# eksik değerler
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df.loc[1, "director"] = "Nolan"

In [ ]:
df.iloc[1]

show_id                                                        s2
type                                                      TV Show
title                                               Blood & Water
director                                                    Nolan
cast            Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
country                                              South Africa
date_added                                     September 24, 2021
release_year                                                 2021
rating                                                      TV-MA
duration                                                2 Seasons
listed_in         International TV Shows, TV Dramas, TV Mysteries
description     After crossing paths at a party, a Cape Town t...
Name: 1, dtype: object

In [ ]:
# unique değerler

df["release_year"].unique()

array([2020, 2021, 1993, 2018, 1996, 1998, 1997, 2010, 2013, 2017, 1975,
       1978, 1983, 1987, 2012, 2001, 2014, 2002, 2003, 2004, 2011, 2008,
       2009, 2007, 2005, 2006, 1994, 2015, 2019, 2016, 1982, 1989, 1990,
       1991, 1999, 1986, 1992, 1984, 1980, 1961, 2000, 1995, 1985, 1976,
       1959, 1988, 1981, 1972, 1964, 1945, 1954, 1979, 1958, 1956, 1963,
       1970, 1973, 1925, 1974, 1960, 1966, 1971, 1962, 1969, 1977, 1967,
       1968, 1965, 1946, 1942, 1955, 1944, 1947, 1943])

In [ ]:
df["release_year"].nunique()

74

In [ ]:
df.value_counts("release_year") # df[relase_year].value_counts()

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1925       1
1947       1
1959       1
1966       1
1961       1
Name: count, Length: 74, dtype: int64

## Veri seçme ve filtreleme
* Koşullu filtreleme
* Boolean maskeler
* Çoklu koşullar

In [ ]:
# Koşullu filtreleme

print(f"Türkiyede çekilen filmler:\n {df[df["country"]== "Turkey"].head(2)}")

Türkiyede çekilen filmler:
     show_id     type                   title director  \
21      s22  TV Show  Resurrection: Ertugrul      NaN
703    s704  TV Show                The Gift      NaN

                                                  cast country  \
21   Engin Altan Düzyatan, Serdar Gökhan, Hülya Dar...  Turkey
703  Beren Saat, Mehmet Günsür, Metin Akdülger, Mel...  Turkey

             date_added  release_year rating   duration  \
21   September 22, 2021          2018  TV-14  5 Seasons
703       June 17, 2021          2021  TV-MA  3 Seasons

                                             listed_in  \
21   International TV Shows, TV Action & Adventure,...
703    International TV Shows, TV Dramas, TV Mysteries

                                           description
21   When a good deed unwittingly endangers his cla...
703  A painter in Istanbul embarks on a personal jo...

In [ ]:

print(f"Türkiyede çekilen filmler:\n {df[df["release_year"] < 1999].head(2)}")

Türkiyede çekilen filmler:
    show_id   type            title        director  \
7       s8  Movie          Sankofa    Haile Gerima
22     s23  Movie  Avvai Shanmughi  K.S. Ravikumar

                                                 cast  \
7   Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
22  Kamal Hassan, Meena, Gemini Ganesan, Heera Raj...

                                              country          date_added  \
7   United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
22                                                NaN  September 21, 2021

    release_year rating duration  \
7           1993  TV-MA  125 min
22          1996  TV-PG  161 min

                                           listed_in  \
7   Dramas, Independent Movies, International Movies
22                    Comedies, International Movies

                                          description
7   On a photo shoot in Ghana, an American model s...
22  Newly divorced and denied visitation rights wi...

In [ ]:
# Boolean maskeler
mask = df["release_year"] < 1999
print(f"1999 dan önce çekilen filmler:\n {df[mask].tail(2)}")

1999 dan önce çekilen filmler:
      show_id   type        title         director  \
8764   s8765  Movie   Wyatt Earp  Lawrence Kasdan
8792   s8793  Movie  Young Tiger           Mu Chu

                                                   cast        country  \
8764  Kevin Costner, Dennis Quaid, Gene Hackman, Dav...  United States
8792  Qiu Yuen, Charlie Chin, Jackie Chan, Hu Chin, ...      Hong Kong

            date_added  release_year rating duration  \
8764   January 1, 2020          1994  PG-13  191 min
8792  November 1, 2016          1973     NR   81 min

                                     listed_in  \
8764                        Action & Adventure
8792  Action & Adventure, International Movies

                                            description
8764  Legendary lawman Wyatt Earp is continually at ...
8792  Aided only by a tough female police officer, a...

In [153]:
df["type"].unique()

array(['Movie', 'TV Show'], dtype=object)

In [155]:
#df["country"].unique()

In [161]:
# çoklu koşullar
mask = (df["type"] == "Movie") & (df["country"] == "United States")

print("ABD Yapımı 10 Film:")
# Virgülden öncesi satır filtresi, sonrası sütun seçimidir
titles = df.loc[mask, "title"].head(10)

print(titles)

ABD Yapımı 10 Film:
0     Dick Johnson Is Dead
9             The Starling
27               Grown Ups
28              Dark Skies
41                    Jaws
42                  Jaws 2
43                  Jaws 3
44       Jaws: The Revenge
48            Training Day
81                    Kate
Name: title, dtype: object

## Pandas ile veri temizleme
* Eksik veriler
* yinelenen değerler
* değer değiştirme
* string işlemleri

In [162]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2633
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [171]:
# df.dropna() -> eksik verileri siler
df["date_added"] = df["date_added"].fillna(df["release_year"]) # eklenme yılını filmin çıkış yılı yaptık
df.isnull().sum()

show_id            0
type               0
title              0
director        2633
cast             825
country          831
date_added         0
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [173]:
# yinelenen değer kontrolü
df["title"].duplicated().sum()

np.int64(0)

In [188]:
# Şart: Başlığı 'Resuraction : Ertugrul' olan satırı bul
# Sütun: O satırın 'release_year' hücresine git
# Değer: Oraya "nan" yaz
df.loc[df["title"] == "Resurrection: Ertugrul", "release_year"] = np.nan

In [189]:
df.loc[df["title"] == "Resurrection: Ertugrul"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
21,s22,TV Show,Resurrection: Ertugrul,NaN,"Engin Altan Düzyatan, Serdar Gökhan, Hülya Dar...",Turkey,"September 22, 2021",NaN,TV-14,5 Seasons,"International TV Shows, TV Action & Adventure,...",When a good deed unwittingly endangers his cla...

In [193]:
df['show_id'] = df['show_id'].str.upper() # tüm harfleri büyük yapma
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,S1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,S2,TV Show,Blood & Water,Nolan,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [195]:
df['show_id'] = df['show_id'].str.strip() # boşlukları kaldırma
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,S1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,S2,TV Show,Blood & Water,Nolan,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

## Pandas ile veri dönüştürme
* Sıralama
* yeniden indeksleme
* tip dönüşümü
* kategorik veri

In [200]:
# sıralma
df.sort_values(by = "release_year", ascending=False).head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
693,S694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
490,S491,TV Show,Elize Matsunaga: Once Upon a Crime,NaN,NaN,NaN,"July 8, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",The crime shocked Brazil: Elize Matsunaga shot...
1110,S1111,Movie,Madame Claude,Sylvie Verheyde,"Karole Rocher, Garance Marillier, Roschdy Zem,...",France,"April 2, 2021",2021,TV-MA,113 min,"Dramas, International Movies","In 1960s Paris, Madame Claude's influence exte..."
1109,S1110,Movie,Just Say Yes,"Appie Boudellah, Aram van de Rest","Yolanthe Cabau, Noortje Herlaar, Kim-Lian van ...",Netherlands,"April 2, 2021",2021,TV-MA,98 min,"Comedies, International Movies, Romantic Movies",Incurable romantic Lotte finds her life upende...

In [202]:
# yeniden indeksleme

df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,S1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,S2,TV Show,Blood & Water,Nolan,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,S3,TV Show,Ganglands,Nolan,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [209]:
df = df.sort_values(by = "release_year", ascending=False)
df.reset_index(drop = True, inplace = True)
df.head(3)

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,693,S694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
1,1095,S1096,TV Show,This Is a Robbery: The World's Biggest Art Heist,NaN,NaN,NaN,"April 7, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, TV Mysteries","In 1990, two men dressed as cops con their way..."
2,1109,S1110,Movie,Just Say Yes,"Appie Boudellah, Aram van de Rest","Yolanthe Cabau, Noortje Herlaar, Kim-Lian van ...",Netherlands,"April 2, 2021",2021,TV-MA,98 min,"Comedies, International Movies, Romantic Movies",Incurable romantic Lotte finds her life upende...

In [211]:
df.drop("index", axis = 1, inplace = True)
df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,S694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
1,S1096,TV Show,This Is a Robbery: The World's Biggest Art Heist,NaN,NaN,NaN,"April 7, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, TV Mysteries","In 1990, two men dressed as cops con their way..."
2,S1110,Movie,Just Say Yes,"Appie Boudellah, Aram van de Rest","Yolanthe Cabau, Noortje Herlaar, Kim-Lian van ...",Netherlands,"April 2, 2021",2021,TV-MA,98 min,"Comedies, International Movies, Romantic Movies",Incurable romantic Lotte finds her life upende...

In [212]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6174 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8807 non-null   object
 7   release_year  8806 non-null   object
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: object(12)
memory usage: 825.8+ KB

In [213]:
# tip dönüştürme
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6174 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8807 non-null   object
 7   release_year  8806 non-null   object
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: object(12)
memory usage: 825.8+ KB

In [215]:
df['release_year'] = df['release_year'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6174 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8807 non-null   object
 7   release_year  8806 non-null   float64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: float64(1), object(11)
memory usage: 825.8+ KB

In [217]:
# Kategorik veri ekleme
df['type'] = df['type'].astype('category') # memory düşecek
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   category
 2   title         8807 non-null   object
 3   director      6174 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8807 non-null   object
 7   release_year  8806 non-null   float64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: category(1), float64(1), object(10)
memory usage: 765.7+ KB

## Gruplama ve özetleme
* groupby
* toplama, ortalama ve sayma ile gruplama
* mean-max değerler ile gruplama
* birden fazla sütuna göre gruplama
* agg() ile özetleme

In [219]:
# Temel gruplama

df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [221]:
# type göre ortalama yıl

df.groupby("type")["release_year"].mean()

/tmp/ipykernel_1620/1636397357.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("type")["release_year"].mean()

type
Movie      2013.121514
TV Show    2016.605234
Name: release_year, dtype: float64

In [225]:
# toplama, ortalama ve sayma

df.groupby("type")["release_year"].sum()

/tmp/ipykernel_1620/4166430122.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("type")["release_year"].sum()

type
Movie      12342448.0
TV Show     5394419.0
Name: release_year, dtype: float64

In [226]:
df.groupby("type")["release_year"].count()

/tmp/ipykernel_1620/3782342322.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("type")["release_year"].count()

type
Movie      6131
TV Show    2675
Name: release_year, dtype: int64

In [227]:
df.groupby("type")["release_year"].min()

/tmp/ipykernel_1620/1724185480.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("type")["release_year"].min()

type
Movie      1942.0
TV Show    1925.0
Name: release_year, dtype: float64

In [228]:
df.groupby("type")["release_year"].max()

/tmp/ipykernel_1620/2550327798.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("type")["release_year"].max()

type
Movie      2021.0
TV Show    2021.0
Name: release_year, dtype: float64

In [251]:
# birden fazla sütuna göre gruplama
df.groupby(["type", "release_year"])["country"].count()

/tmp/ipykernel_1620/2558075068.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["type", "release_year"])["country"].count()

type     release_year
Movie    1925.0            0
         1942.0            2
         1943.0            3
         1944.0            3
         1945.0            3
                        ...
TV Show  2017.0          236
         2018.0          324
         2019.0          348
         2020.0          391
         2021.0          214
Name: country, Length: 148, dtype: int64

In [255]:
# agg()

df.groupby("type")["release_year"].agg(["mean", "max", "min", "count"])

/tmp/ipykernel_1620/4208417538.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("type")["release_year"].agg(["mean", "max", "min", "count"])

                mean     max     min  count
type
Movie    2013.121514  2021.0  1942.0   6131
TV Show  2016.605234  2021.0  1925.0   2675

## Birleştirme ve Bir araya getirme
* Concatenation
* Merge
* Join
* İndex bazlı birleştirme

In [257]:
# concat
df1 = pd.DataFrame({"id": [1,2,3], "isim": ["Ali", "Veli", "Ayşe"]})
df2 = pd.DataFrame({"id": [5,6,7], "isim": ["Ahmet", "Mehmet", "Nisa"]})

In [258]:
# üst üste ekle
df_concat = pd.concat([df1, df2])
df_concat

   id    isim
0   1     Ali
1   2    Veli
2   3    Ayşe
0   5   Ahmet
1   6  Mehmet
2   7    Nisa

In [259]:
# yan yana ekleme

df_concat = pd.concat([df1, df2], axis = 1)
df_concat

   id  isim  id    isim
0   1   Ali   5   Ahmet
1   2  Veli   6  Mehmet
2   3  Ayşe   7    Nisa

In [287]:
# merge/join

df1 = pd.DataFrame({"id": [1,2,3], "isim": ["Ali", "Veli", "Ayşe"]})
df2 = pd.DataFrame({"id": [1,2,4] ,  "sehir": ["Adana", "Ankara", "Elazığ"]})

print(df1)
print(df2)

   id  isim
0   1   Ali
1   2  Veli
2   3  Ayşe
   id   sehir
0   1   Adana
1   2  Ankara
2   4  Elazığ

In [288]:
df_merge = pd.merge(df1, df2, on = "id", how = "inner") # id leri aynı olan
df_merge

   id  isim   sehir
0   1   Ali   Adana
1   2  Veli  Ankara

In [289]:
df_merge = pd.merge(df1, df2, on = "id", how = "left") # soldaki veri için tüm kayıtlar
df_merge

   id  isim   sehir
0   1   Ali   Adana
1   2  Veli  Ankara
2   3  Ayşe     NaN

In [286]:
df_merge = pd.merge(df1, df2, on = "id", how = "right") # sağdaki için tüm kayıtlar
df_merge

   id  isim   sehir
0   1   Ali   Adana
1   2  Veli  Ankara
2   4   NaN  Elazığ

In [291]:
# indeks bazlı birleştirme

df1 = pd.DataFrame({ "isim": ["Ali", "Veli", "Ayşe"]}, index = ["a","b","c"])
df2 = pd.DataFrame({"not": [85,90,23]} , index = ["a","b","d"])

print(df1)
print(df2)

   isim
a   Ali
b  Veli
c  Ayşe
   not
a   85
b   90
d   23

In [297]:
pd.merge(df1,df2, left_index = True, right_index = True, how = "outer") # hepsi

   isim   not
a   Ali  85.0
b  Veli  90.0
c  Ayşe   NaN
d   NaN  23.0